### ISSUE TITLE
Extract the cmd line part

### ISSUE THREAD

**Issue by albertnetymk** [solusipse/ytwebm#8]
Is it possible to extract the part of fetching videos from all the supported websites? IOW, something like `youtube-dl`, but works with many more websites?

**Comment by solusipse** [comment]
I didn't quite get it. You mean to cut a video but keep it in original format? Web-to-webm uses youtube-dl so you can download videos only from these services: http://rg3.github.io/youtube-dl/supportedsites.html

**Comment by albertnetymk** [comment]
Thanks for the clarification. It's named as `youtube-dl`, so I assumed that it only works with `YouTube`, and you added the support for other websites. I think `youtube-dl` is the cmd line part I was referring to while opening this issue. Sorry for my misunderstanding.

**Comment by solusipse** [comment]
Thanks!
